### ISSUE TITLE
请问工具类或其他包里面需要读取配置文件的内容该怎么做？

### ISSUE THREAD

**Issue by Think-Me** [go-nunu/nunu#67]
例如我配置文件后面追加这些内容
```yaml
tencent:
  ak: xxxxxxxxxxxxxxx
  sk: xxxxxxxxxxxxxxx
  cos:
    url: https://xxxxxx.myqcloud.com
```
我想用conf.GetString("tencent.ak")取值，但是conf在其他包中并不能使用。
